import './globals.css'
import { Inter } from 'next/font/google'
import { Providers } from "./providers";
import WithSubnavigation  from './Components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'VelaMD App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
        <WithSubnavigation />
          {children}
        </Providers>
      </body>
    </html>
  )
}
